// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvVmlbOmTOsH7L1DIYql7i7hhZjuHJL1g',
    appId: '1:81693461504:web:423973fcb38b6633945ce5',
    messagingSenderId: '81693461504',
    projectId: 'sneakerapp-e0608',
    authDomain: 'sneakerapp-e0608.firebaseapp.com',
    storageBucket: 'sneakerapp-e0608.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMWrEjxoZBdO54j36t4-mkVD_7E2bj5TY',
    appId: '1:81693461504:android:f2c9674bc8d76e1f945ce5',
    messagingSenderId: '81693461504',
    projectId: 'sneakerapp-e0608',
    storageBucket: 'sneakerapp-e0608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifls2nPDSVKPbb79czJY838wASFYazqQ',
    appId: '1:81693461504:ios:80df0924badba13d945ce5',
    messagingSenderId: '81693461504',
    projectId: 'sneakerapp-e0608',
    storageBucket: 'sneakerapp-e0608.appspot.com',
    iosBundleId: 'com.example.sneakers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCifls2nPDSVKPbb79czJY838wASFYazqQ',
    appId: '1:81693461504:ios:f00dd731377ff9fa945ce5',
    messagingSenderId: '81693461504',
    projectId: 'sneakerapp-e0608',
    storageBucket: 'sneakerapp-e0608.appspot.com',
    iosBundleId: 'com.example.sneakers.RunnerTests',
  );
}
